name: Build Server

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        working-directory: src/TestEntityPostgre
        run: dotnet restore
        
      - name: Build project
        working-directory: src/TestEntityPostgre
        run: dotnet build --configuration Release --no-restore
